### PR TITLE
Add Search by Alias feature

### PR DESCRIPTION
**Pull request by GuyKh**
Solve #8

### CODE REVIEW

**Comment by GuyKh** [comment]
@mbos2 
Need an advise on HTML design here.

Using:
```
    <div class="divider dark"></div>
    <div class="d-flex align-items-center justify-content-center">
      <input required id="alias_search_term" type="text" placeholder="URL Alias Search Term" aria-label="RL Alias Search Term" aria-describedby="button-addon2">
      <button onclick="searchUrl()" class="btn btn-outline-dark" type="button" id="button-addon2">Search</button>
    </div>
```

I'm getting this:
image


I believe we can do better

**Comment by mbos2** [comment]
I am not sure, but I also did not assign you on any issue at the moment

**Comment by mbos2** [comment]
Unless assigned to the issue I will not be accepting PRs. 
I wrote Contribution Guidelines. 

And as main file is becoming pretty large and less and less readable, I will be doing refactoring on some code before I continue with other issues.

**Comment by GuyKh** [comment]
@mbos2 You're welcome :/

**Pull request closed without merging**
